footprint: [[-0.5, -0.35], [-0.5, 0.35], [0.5, 0.35], [0.5, -0.35]]
footprint_padding: 0.01

robot_base_frame: X1/fake
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 50
raytrace_range: 50

obstacles_laser:
  observation_sources: point_cloud_sensor
  point_cloud_sensor: {
    data_type: PointCloud2,
    clearing: true,
    marking: true,
    topic: /X1/points_filtered
  }

