global_frame: X1/odom
rolling_window: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

inflation:
  inflation_radius: 3.0
  cost_scaling_factor: 18.0
obstacle:
  max_obstacle_height: 2
