yolo_model:

  config_file:
    name: yolo-subt-tiny.cfg
  weight_file:
    name: yolo-subt-tiny_final.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - bag
      - helmet
      - rope
      - randy

